### ISSUE TITLE
只显示执行完毕

### ISSUE THREAD

**Issue by zysNLP** [Seven-Steven/jianshu-spider#1]
你好，我运行你的代码，输入python jianshu.py --post-url https://www.jianshu.com/p/5bd14cbf7186，只显示执行完毕，但post为None，也没有输出文件，为什么？

**Comment by seven-steven** [comment]
很抱歉发生这个问题. 
刚查了一下, 脚本原理是抓取简书文章的 html 文本, 然后从文本中提取文章信息. 但是简书现在对 css 进行了加密, 脚本按照原来的抓取逻辑找不到对应的信息, 导致异常退出. 
我会跟进这个问题并尽快修复, 但是尚不能保证具体日期, 还请见谅.

**Comment by zysNLP** [comment]
好的，多谢
